name: Buidl and deploy code

on: [push, pull_request]
  # pull_request:
  #   branches:
  #     - "master"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo 
        uses: actions/checkout@v4
      - name: say hi to steve
        run: echo "hey steve"
