name: Buidl and deploy code

on: [push, pull_request]
  # pull_request:
  #   branches:
  #     - "master"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo 
        uses: actions/checkout@v4
      - name: load env file contents
        run: |
          cat .env >> $GITHUB_ENV
      - name: set up python v3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: upgrade pip 
        run: python -m pip install --upgrade pip
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run pytest
        run: |
          pip install pytest
          pytest
